export const createDemoState = () => ({
  version: 1,
  repo: {
    name: 'parcel-ops',
    branch: 'release/checkout-guardrails',
    language: 'JavaScript / TypeScript',
    lastScan: '2 min ago',
  },
  lanes: [
    {
      id: 'ui-checkout',
      agent: 'Mira / Experience',
      task: 'Prevent accidental double submit on checkout.',
      status: 'airborne',
      files: ['src/checkout/CheckoutForm.jsx'],
      symbols: ['CheckoutForm', 'submitOrder'],
      contracts: ['submit-order'],
      evidence: [{ command: 'npm run test:checkout', result: 'passing', at: '09:42' }],
      note: 'UI-only lane. Do not change pricing behavior.',
      createdAt: '2026-07-17T09:31:00.000Z',
      updatedAt: '2026-07-17T09:42:00.000Z',
    },
    {
      id: 'pricing-rules',
      agent: 'Theo / Pricing',
      task: 'Make quote totals include the delivery threshold.',
      status: 'airborne',
      files: ['src/quote.js', 'src/api/quote.js'],
      symbols: ['quoteTotal', 'quoteSummary'],
      contracts: ['pricing', 'quote-response'],
      evidence: [{ command: 'node --test quote.test.js', result: 'passing', at: '09:39' }],
      note: 'Owns the quote calculation until handoff.',
      createdAt: '2026-07-17T09:18:00.000Z',
      updatedAt: '2026-07-17T09:39:00.000Z',
    },
    {
      id: 'tax-adjustment',
      agent: 'Sol / Rules',
      task: 'Apply regional tax adjustment to the checkout quote.',
      status: 'holding',
      files: ['src/quote.js', 'src/tax/adjustments.js'],
      symbols: ['quoteTotal', 'calculateTaxAdjustment'],
      contracts: ['pricing', 'tax-adjustment'],
      evidence: [],
      note: 'Requested after pricing lane had already departed.',
      createdAt: '2026-07-17T09:35:00.000Z',
      updatedAt: '2026-07-17T09:40:00.000Z',
    },
    {
      id: 'receipt-copy',
      agent: 'Ada / Comms',
      task: 'Clarify the delivery threshold in the receipt copy.',
      status: 'queued',
      files: ['src/receipts/DeliveryNote.jsx'],
      symbols: ['DeliveryNote'],
      contracts: ['receipt-copy'],
      evidence: [],
      note: 'Can launch once the copy owner confirms scope.',
      createdAt: '2026-07-17T09:44:00.000Z',
      updatedAt: '2026-07-17T09:44:00.000Z',
    },
  ],
  activity: [
    { time: '09:44', type: 'reserve', lane: 'receipt-copy', text: 'Ada requested a new lane.' },
    { time: '09:40', type: 'hold', lane: 'tax-adjustment', text: 'Runway held Sol for a shared pricing symbol.' },
    { time: '09:39', type: 'evidence', lane: 'pricing-rules', text: 'Theo attached a passing quote test.' },
    { time: '09:31', type: 'launch', lane: 'ui-checkout', text: 'Mira was cleared for the checkout lane.' },
  ],
})
